# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# 数据库配置 (MySQL)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_web?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  # 数据库初始化
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: true

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-prefix: 
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

# Knife4j 配置
knife4j:
  enable: true
  production: false
  setting:
    language: zh_cn
  openapi:
    title: Chat Web API
    description: Chat Web 后端接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yuan.chatweb.controller

# 大模型配置
llm:
  default:
    model-name: GPT-3.5 Turbo
    model-id: gpt-3.5-turbo
    api-url: https://api.openai.com/v1/chat/completions
    api-key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# 日志配置
logging:
  level:
    root: INFO
    com.yuan.chatweb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"